#!/bin/bash

export PATH="/usr/local/node/bin:${PATH}"
export WORKDIR="/srv/shared/code-ai-agent/code-ai-agent"
cd ${WORKDIR}
npm install
npx nx reset
npx nx run-many --target=build --projects=lib,googleai-agent,anthropic-agent,openai-agent,github-agent
npx nx run-many --target=serve --projects=googleai-agent,anthropic-agent,openai-agent,github-agent
